In [1]:
import numpy as np

In [3]:
# crear un array aleatorio con una estructura de 5 x 5
a = np.random.randint(1,100, (5,5))

In [4]:
#
a.shape

(5, 5)

In [6]:
a

array([[69, 18,  7, 99,  9],
       [28, 18, 43, 57, 47],
       [94, 91, 88, 40, 89],
       [86,  5, 33, 14, 62],
       [91, 97, 16, 82, 70]])

In [8]:
# Cambiar la estructura del array
a.reshape(1,25)

array([[69, 18,  7, 99,  9, 28, 18, 43, 57, 47, 94, 91, 88, 40, 89, 86,
         5, 33, 14, 62, 91, 97, 16, 82, 70]])

In [15]:
# Funciones principales

matrix = a.reshape(5,5)


In [13]:
matrix.max(1)

array([99, 57, 94, 86, 97])

In [18]:
# indice donde se encuentra el valor más grande del array
a.argmax()

3

In [17]:
# indice donde se encuentra el valor más pequeño del array
matrix.argmin()

16

In [21]:
#  de un pico a otro pico (desde el valor minimo hasta el máximo)
matrix.ptp(0)

array([66, 92, 81, 85, 80])

In [24]:
# percentil
np.percentile(a,75)

88.0

In [25]:
# ordenar de menor a mayor
a.sort()

In [30]:
# mediana
np.median(a)
#media
np.mean(a)

54.12

In [29]:
# desviación estandar
np.std(a)
# varianza
np.var(a)

1068.3455999999999

In [37]:
# concatenar

b = np.array([[1,2],[3,4]])
c = np.array([5,6])

np.concatenate((a,b,), axis = 1 )

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 2

In [38]:
c = np.expand_dims(c, axis = 0)

In [39]:
np.concatenate((b,c), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
# La transpuesta pone nuestro array en sentido opuesto
np.concatenate((b,c.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [42]:
# copy

x = np.arange(0,11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
ax = x[0:7]
ax

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
ax[:] = 0
ax

array([0, 0, 0, 0, 0, 0, 0])

In [48]:
x

array([ 0,  0,  0,  0,  0,  0,  0,  7,  8,  9, 10])

In [ ]:
# me equivoque, solo queria cambiar el valor al trozo ax.

In [51]:
x_copy = x.copy()
x_copy

array([ 0,  0,  0,  0,  0,  0,  0,  7,  8,  9, 10])

In [52]:
# se crea un objeto diferente a x
x_copy[:] = 100
x_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
x

array([ 0,  0,  0,  0,  0,  0,  0,  7,  8,  9, 10])

In [55]:
# condiciones en np
# filtrado de data frame

a = np.linspace(1,100, 100, dtype= "int8")
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int8)

In [56]:
# definimos condición
con = a > 10
con # Sale array con valores boleanos

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [57]:
a[con] # matriz con valores mayores a 10

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
      dtype=int8)

In [58]:
a [(a > 10) & (a < 70)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69], dtype=int8)

In [60]:
a[a>90] = 99
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
      dtype=int8)

In [64]:
# operaciones

A = np.array([[1,0], [0,1]])
B = np.array([[1,2], [3,4]])

In [65]:
# suma
print(A+B)

[[2 2]
 [3 5]]


In [66]:
# Mutiplicación
print(A*B)

[[1 0]
 [0 4]]


In [67]:
# multiplicar por escalar

A * 2

array([[2, 0],
       [0, 2]])

In [69]:
A.T

array([[1, 0],
       [0, 1]])